export const STACK_DATA = [
  {
    category: "Frontend Development",
    skills: [
      "HTML5",
      "CSS3",
      "SCSS/SASS",
      "Bootstrap",
      "TailwindCSS",
      "Cross-Browser Compatibility",
      "Styled Components",
      "Responsive Design",
      "UI/UX Design",
      "Ant-Design",
      "Chakra UI",
      "MUI",
      "Mantine",
    ],
  },
  {
    category: "JavaScript & Backend",
    skills: [
      "JavaScript (ES6+)",
      "TypeScript",
      "NodeJS",
      "React",
      "NextJS",
      "Axios",
      "MongoDB",
      "React Router",
      "AJAX",
      "Express.js",
      "NestJS",
      "JWT",
      "Socket.io",
      "React Query",
      "React Hook Form",
    ],
  },
  {
    category: "Tools & DevOps",
    skills: [
      "Git",
      "GitHub",
      "Redux",
      "Docker",
      "Redux Toolkit",
      "Webpack",
      "Vite",
      "Cypress",
      "Jest",
      "Cloudflare",
      "Vercel",
      "Postman",
      "ESLint",
      "Prettier",
      "Swagger",
      "Jira",
      "GitHub Actions",
    ],
  },
];
